### ISSUE TITLE
Ayudaaaaaa

### ISSUE THREAD

**Issue by aleira** [maestria-geotel-201902/unidad-0-asignacion-3-mi-primer-rmd-aleira#1]
Saludos, profesor cuando ejecuto el example(lm) en RStudio me presenta el siguiente error. 
![image](https://user-images.githubusercontent.com/39606510/67168759-3eb0ad00-f375-11e9-80ac-92c86f0c82b4.png)

**Comment by geofis** [comment]
Este caso me parece que sólo debes ampliar el tamaño de la pestaña `Plots`. Prueba así:

![image](https://user-images.githubusercontent.com/13460617/67251087-d7a9fb80-f43b-11e9-8728-87440e6a15c1.png)
