### ISSUE TITLE
Error ejecutando el mapa de area(km2)

### ISSUE THREAD

**Issue by aleira** [maestria-geotel-201902/unidad-0-asignacion-3-mi-primer-rmd-aleira#2]
Saludos profesor. 
cuando ejecuto el 
reg.sf$area <- st_area(reg.sf)
plot(reg.sf['area']), me presenta un error y se borra las regiones y Toponimia que tenia el plot y me presenta el siguiente error:
![image](https://user-images.githubusercontent.com/39606510/67171729-53e20780-f386-11e9-937c-31ce34172dc9.png)

**Comment by geofis** [comment]
Gracias por notificar. Estuve haciendo mantenimientos nocturnos al servidor. Supongo que a partir de ahora, debería funcionar correctamente. Si hubiese inconvenientes, favor reabrir el issue.

**Comment by geofis** [comment]
Prueba de nuevo @aleira con el nuevo repo, y avisa si no funciona.
